language: node_js
node_js:
  - "stable"
services:
  - docker 
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: FFs0kD9qMOKalydQ4aAineFbS/gMh9pFv4vOyOQ7OL89Cony+GBgqsdboMLHtwpYmxnxUzzcNk6eb/wQQPrJQUifr5Ek3p2LDwNizKDefDk/n0m+xiL5se4c/cZ7DWbUOyUyJJLQb8S6fR44PPgWSY3U+urL1JYX2rKsU89GcPlWHesuMaNqfMH2B+wGqH/DjokxSo4uLDVWocTAHtWb9jT90L/WzA48g1NRzpD5ZaJC9GCK55sqBDIYSyg4j/Rb3V7Lh3i3ptRMtG7/Ovq9i9CdN4jPebVYlzxWQjOtGC3vXIS7iCp+cXQzREduJx1ZQGn5SNJrM/NqCLNP8jEF5SIwSKgIQzU9nojl6Gmz5VYQeNVkzH14iKuUO/J6Jf2W4eb6ijWTalgEZl3pgafL7hXQK78PeqaacncanhevL4f+q3Glj5RX+yJvLk2AK5+gP9AWe8XGs52w+lSgkkhwMZWRXsRewB07sPN66lx+Cd7V1E6CrEAyLn2gfYL50SKigJT+l91wDPMe9ky2PASd5z1vriFiqaB6+2RvsAVY4TtMPw4F6NFLrcGtbiG4uW5g4IoDedtNOgPebI1AhSsKvi/H+hf6vtC5hgA5Vv3ORjG211Qs8sz22Zph5e5bZLCtIdl12cp8/nwnQrfa7vEhlM+K9xnA5AngQNeznUHLEQI=
  app: stvi
  on:
    repo: stevenpham408/stvi-frontend
on:
  branch: master